"""plus table agent and refresh house table

Revision ID: 1c12ba61c871
Revises: ddcf2dfd1cb9
Create Date: 2025-09-23 16:42:19.264903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c12ba61c871'
down_revision: Union[str, Sequence[str], None] = 'ddcf2dfd1cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('hotels_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotels_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent')
    # ### end Alembic commands ###
