"""unique column for email

Revision ID: e43eec715ddf
Revises: c3545f3f487b
Create Date: 2025-10-07 11:22:38.666536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e43eec715ddf"
down_revision: Union[str, Sequence[str], None] = "c3545f3f487b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###
