"""update table users

Revision ID: c3545f3f487b
Revises: a9b46b1fbe66
Create Date: 2025-10-06 14:51:12.070743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3545f3f487b"
down_revision: Union[str, Sequence[str], None] = "a9b46b1fbe66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=150), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=150), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("phone_number", sa.String(length=20), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
