"""initial

Revision ID: e37c7c411df5
Revises:
Create Date: 2025-09-30 11:35:46.933772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e37c7c411df5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "houses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=20), nullable=False),
        sa.Column("street", sa.String(length=150), nullable=True),
        sa.Column("number_house", sa.String(length=10), nullable=True),
        sa.Column("square", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("hotels_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotels_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent")
    op.drop_table("houses")
    # ### end Alembic commands ###
