"""plus table agent and refresh house table

Revision ID: ddcf2dfd1cb9
Revises: 07ad818eb69e
Create Date: 2025-09-23 16:35:38.311328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcf2dfd1cb9'
down_revision: Union[str, Sequence[str], None] = '07ad818eb69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('city', sa.String(length=20), nullable=False))
    op.add_column('houses', sa.Column('street', sa.String(length=150), nullable=True))
    op.add_column('houses', sa.Column('number_house', sa.String(length=10), nullable=True))
    op.alter_column('houses', 'square',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('houses', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('location', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.alter_column('houses', 'square',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('houses', 'number_house')
    op.drop_column('houses', 'street')
    op.drop_column('houses', 'city')
    # ### end Alembic commands ###
